version: "3.5"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - "9092"
      - "29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper-server

  postgress:
    image: postgres
    expose:
      - 5432
    ports:
      -  5432
    volumes:
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./Database/accounts.sql:/docker-entrypoint-initdb.d/2-accounts.sql
      - ./Database/custom.sql:/docker-entrypoint-initdb.d/3-custom.sql
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: 'tech'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'payments'
    secrets:
      - postgres_user
      - postgres_password

  api-producer:
    build: ./ApiAndProducer
    ports:
      - "8080"
    networks:
      - kafka-net
    volumes:
      - ./ApiAndProducer/bin:/app/
    command: ["./wait-for-it.sh", "postgress:5432","kafka-server:9092","-t","100", "--", "java", "-jar", "app.jar"]
    depends_on:
      - postgress
      - kafka-server

  payment_service:
    build: ./payment_service
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: 'tech'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'payments'
      KAFKA_HOST: 'kafka-server'
      KAFKA_PORT: "9092"
      API_BASE: "api-producer"
      API_PORT: "8080"
      POSTGRES_HOST: "postgress"
      POSTGRES_PORT: "5432"
    command: sh -c "sleep 5 && python runner.py"
    secrets:
      - postgres_user
      - postgres_password
    depends_on:
      - postgress
      - kafka-server
      - zookeeper-server

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password

